spring.application.name=GoGraduation

spring.datasource.url=omitido
spring.datasource.username=omitido
spring.datasource.password=omitido

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
